spring:
  datasource:

    master:
      hikari:
        jdbc-url: jdbc:mysql://34.64.192.14:3306/datamigration
        read-only: false
        username: ${MYSQL_NAME}
        password: ${MYSQL_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      hikari:
        jdbc-url: jdbc:mysql://34.64.254.7:3306/datamigration
        read-only: true
        username: ${MYSQL_NAME}
        password: ${MYSQL_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    consumer:
      auto-offset-reset: earliest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaimage:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include: health,info
    health:
      show-details: always
    endpoint:
      shutdown:
        enabled: true