spring:
  datasource:
    url: jdbc:mysql://34.64.88.166:3307/tubeplus
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false


#  data:
#    redis:
#      host: localhost
#      port: 6379