server:
  port: 0
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true

spring:
  profiles:
    active: local, secret
  application:
    name: DATA-MIGRATION-SERVICE
  data:
    redis:
      host: 34.64.88.166
      port: 6379
      password: ${REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
      #        show_sql: true
      dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true # false ?? ??? ??

logging:
  level:
    org:
      springframework:
        batch: DEBUG


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/data-migration/**